### PR TITLE
status-manager: ANP SSA unit test and network-policy-api v0.2.0

### PR DESCRIPTION
**Pull request by smulje**
## Summary

Enable ANP/BANP SSA unit tests by bumping `network-policy-api` to **v0.2.0** (not v0.1.7, which does not compile against client-go v0.35) and migrating fake clients to `NewClientset`.

Also includes the #6479 startup cleanup fix: remove stale zone `managedFields` even when they contain non-empty status (not just empty `{"f:status":{}}` leftovers).

### Changes

**Commit 1: Bump network-policy-api v0.1.5 → v0.2.0**
- Brings `NewClientset` with `managedfields.TypeConverter` (k8s 0.35 compatible)
- Also bumps `k8s.io/{api,apimachinery,client-go}` to v0.35.3 (required by v0.2.0)
- Adds v1alpha2 CNP types in vendor (unused by ovn-k today)

**Commit 2: Fake clients + ANP fix + unit test**
- `fake_client.go`: migrate internal/OpenShift CRDs + **ANP/BANP** to `NewClientset`
- `admin_network_policy_manager.go`: remove `isEmptyStatusManagedField` filter from startup cleanup
- `status_manager_test.go`: new test — stale non-empty `managedFields` for deleted zone are removed on startup

### Related

- #6688 — fake client SSA support
- #6479 — ANP stale status cleanup fix

## Test plan

- [ ] CI Build-PR / Lint / Test-PR pass
- [x] `GOOS=linux go test -c ./pkg/clustermanager/status_manager/` compiles
- [ ] `go test ./pkg/clustermanager/status_manager/ -ginkgo.focus "ANP/BANP managedFields on startup"`

## Notes

- **Draft** — pending CI validation
- v0.1.7 was attempted first but fails with `undefined: testing.TypeConverter`
- EF managedFields tests also updated (bonus coverage via same fake client infra)

### CODE REVIEW

**Comment by smulje** [comment]
1. Unit tests need a fake Kubernetes client that understands SSA / managedFields
2. That requires NewClientset (not NewSimpleClientset)
3. network-policy-api v0.2.0 is the version that provides that for ANP/BANP and works with ovn-k’s k8s 0.35
4. Once that’s in place, you can add the unit test and use the same SSA behavior the real code relies on
5. The nuance: production ANP/BANP already used SSA (ApplyStatus) before this PR. The version bump isn’t to enable SSA in the running controller — it’s to make the test fake client behave like the real API server so the cleanup logic can be tested in unit tests.
7. In one line: bump network-policy-api → get SSA-capable fake client → write unit test that matches real ANP status cleanup behavior.


Breakdown by category:

Category	       Files	           What it is
Your code.       11          Real logic, tests, and API compat fixes
Vendor             91          go mod vendor after bumping deps
LICENSES        42         CI-required license files for new/updated packages
test/e2e             2          go.mod / go.sum only (transitive k8s bump)


The 11 files that matter (why each changed)
1. Dependency bump — go.mod + go.sum (2 files)
What: network-policy-api v0.1.5 → v0.2.0, and core k8s libs v0.35.1 → v0.35.3.
Why: v0.2.0 is the first release that:
      Compiles against ovn-k’s client-go v0.35
       Provides NewClientset with SSA/managedFields support for unit tests
(v0.1.7 was tried first but failed with undefined: testing.TypeConverter.)

2. Fake client for tests — fake_client.go (1 file)
What:ANPClient: NewSimpleClientset → NewClientset
Also handles BaselineAdminNetworkPolicy objects in the type switch
Why: NewSimpleClientset does not track managedFields, so you cannot unit-test SSA cleanup. NewClientset uses FieldManagedObjectTracker, which mirrors real API server behavior.

Only ANP was migrated — migrating all CRDs caused unrelated test failures.

3. Bug fix — admin_network_policy_manager.go (1 file)
What: Removed the isEmptyStatusManagedField(mf) guard from startup cleanup.
Why (#6479): When a zone is deleted, its managedFields entry often has real status data (conditions), not just empty {"f:status":{}}. The old guard skipped those, leaving stale entries forever. Now any status managedField whose manager is a gone zone gets cleaned up.

4. New unit test — status_manager_test.go (1 file)
What: Test "Should clean up stale ANP/BANP managedFields on startup when zone is gone".
Why: Proves the #6479 fix works. It seeds ANP/BANP with managedFields for zone1, zone2, and zone3-deleted, starts status manager with only zones 1+2, and verifies cleanup patches are issued for zone3-deleted.

5. API compat for v0.2.0 — 4 files
  - status.go | WithConditions(newCondition) → WithConditions(conditionApplyConfiguration(...)) | v0.2.0 expects *ConditionApplyConfiguration, not raw metav1.Condition
  - types.go | Added newBaselineAdminNetworkPolicyEgressPeer() wrapper | BANP egress peers are now a separate type in v0.2.0
  - baseline_admin_network_policy_test.go | AdminNetworkPolicyEgressPeer → BaselineAdminNetworkPolicyEgressPeer | Same type split in tests
  - factory.go | anpapi.AddToScheme → anpapi.Install | AddToScheme deprecated in v0.2.0
  
6. e2e module sync — test/e2e/go.mod + go.sum (2 files)
What: Updated transitive k8s dependencies to match go-controller’s bump.

Why: test/e2e uses a replace directive pointing at go-controller. When go-controller bumps k8s, e2e’s go.sum must be regenerated or CI fails with missing checksums.

The other 133 files (why they exist)
Vendor (91 files)
Running go mod vendor after the bump copies the entire updated network-policy-api v0.2.0 tree into the repo, including:

New v1alpha2 ClusterNetworkPolicy types (unused by ovn-k today, but shipped in the library)
Updated applyconfiguration clients, informers, listers
Updated k8s 0.35.3 client-go bits
You did not write these — they come from upstream libraries.

LICENSES (42 files)
ovn-k CI requires a LICENSES/ entry for every vendored dependency. When packages are added, removed, or version-bumped, those files must be regenerated (make third-party-licenses).

Mental model
Goal: unit-test ANP/BANP managedFields cleanup (#6688 + #6479)
  │
  ├─ Need SSA-capable fake client
  │    └─ Bump network-policy-api → v0.2.0 (+ k8s 0.35.3)
  │         └─ 91 vendor files + 42 LICENSE files (automatic fallout)
  │
  ├─ Fix compile breaks from v0.2.0 API changes (4 files)
  │
  ├─ Switch ANPClient to NewClientset (fake_client.go)
  │
  ├─ Fix startup cleanup logic (admin_network_policy_manager.go)
  │
  └─ Add unit test proving it works (status_manager_test.go)
       └─ Sync test/e2e go.sum (2 files)

**Comment by smulje** [comment]
6743 address this one
