### PR TITLE
go-controller: Require go 1.15, run go mod tidy and go mod vendor

### PR DESCRIPTION
**Pull request by andreaskaris**
Require go 1.15, run go mod tidy and go mod vendor, additionally,
update the README

In earlier versions of go, this will still fail early when it attempts
compilation of github.com/ovn-org/libovsdb

Fixes issue #2243

Signed-off-by: Andreas Karis <ak.karis@gmail.com>

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by andreaskaris** [comment]
So, I retested this and instead now it fails on:
~~~
[root@ovnkubernetes go-controller]# make
hack/build-go.sh cmd/ovnkube cmd/ovn-k8s-cni-overlay cmd/ovn-kube-util hybrid-overlay/cmd/hybrid-overlay-node cmd/ovndbchecker cmd/ovnkube-trace
grep: github.com/ovn-org/ovn-kubernetes/go-controller/go.sum: No such file or directory
+ for bin in "$@"
++ basename cmd/ovnkube
+ binbase=ovnkube
+ CGO_ENABLED=1
+ '[' ovnkube = ovn-k8s-cni-overlay ']'
+ env CGO_ENABLED=1 go build -v -mod vendor -gcflags '' -ldflags '-B 0x960fd362a7cb76a240590f8767a57fa6da26ed4a                 -X github.com/ovn-org/ovn-kubernetes/go-controller/pkg/config.Commit=33dbced8ac7c9778db69eca5d34d40b29e57d4af                 -X github.com/ovn-org/ovn-kubernetes/go-controller/pkg/config.Branch=master                 -X github.com/ovn-org/ovn-kubernetes/go-controller/pkg/config.BuildUser=root                 -X github.com/ovn-org/ovn-kubernetes/go-controller/pkg/config.BuildDate=2021-07-04                 -X k8s.io/client-go/pkg/version.gitVersion=' -o /root/ovn-kubernetes/go-controller/_output/go/bin/ovnkube ./cmd/ovnkube
github.com/ovn-org/libovsdb/client
# github.com/ovn-org/libovsdb/client
vendor/github.com/ovn-org/libovsdb/client/client.go:116:14: undefined: tls.Dialer
make: *** [Makefile:35: all] Error 1
~~~

That's regardless of the proposed changes.

The problem is that in May, this new dependency was introduced to vendor/github.com/ovn-org/libovsdb and the minimum go version for that dependency is go1.16. Hence, inclusion of github.com/ovn-org/libovsdb 0.5.0 should bump the required go version to 1.16 IMO:

https://github.com/ovn-org/libovsdb/blob/b6a89b4aebb68d1e018fd442aed0df0023e2f631/go.mod#L3
~~~
module github.com/ovn-org/libovsdb

go 1.16

require (
	github.com/cenk/hub v1.0.1 // indirect
	github.com/cenkalti/hub v1.0.1 // indirect
	github.com/cenkalti/rpc2 v0.0.0-20210220005819-4a29bc83afe1
	github.com/google/uuid v1.2.0
	github.com/stretchr/testify v1.6.1
)
~~~

Somehow, that go.mod file is not pulled in, though, and it compiles fine in go 1.15, anyway. 
I think this is related to the discussion in: https://github.com/golang/go/issues/42970 and the developers decided to pull go.mod files in the vendor directory altogether starting with 1.17  (https://github.com/golang/go/commit/eb71887b99fa656ed627c9c1d41319b9198979c8)

I bumped the required version to 1.15 and adjusted the README, but because of the above, this still fails on compilation of the vendor module before it takes into account the actual requirement for go 1.15.

However, I still think it's worth bumping the version so that humans get a cluster about what's wrong when looking at the README or go.mod
